// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBAPIFLUENT.Context;

#nullable disable

namespace WEBAPIFLUENT.Migrations
{
    [DbContext(typeof(PDFContext))]
    partial class PDFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WEBAPIFLUENT.Models.AssembledBoardDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("IId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IId");

                    b.ToTable("assembledBoards");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.BareBoardDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("BoardType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("IId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IId");

                    b.ToTable("bareboards");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Board", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("VId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VId");

                    b.ToTable("boards");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Heading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("IId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IId");

                    b.ToTable("headings");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Identity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("RId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RId");

                    b.ToTable("identity");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.PowerUpTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Exp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("IId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PUT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IId");

                    b.ToTable("poweruptests");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Rivision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BId");

                    b.ToTable("rivisions");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.SubHeading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("HId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HId");

                    b.ToTable("subheading");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.SubHeadingImages", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ImageData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("SHId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SHId");

                    b.ToTable("subheadingimages");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Varient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PId");

                    b.ToTable("varients");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.XLSheet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Col1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Col2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Col3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Col4")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("XId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("XId");

                    b.ToTable("xLSheets");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.XLTamplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("SHId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SHId");

                    b.ToTable("xLTamplates");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.AssembledBoardDetails", b =>
                {
                    b.HasOne("WEBAPIFLUENT.Models.Identity", "Identity")
                        .WithMany("AssembledBoardDetails")
                        .HasForeignKey("IId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.BareBoardDetails", b =>
                {
                    b.HasOne("WEBAPIFLUENT.Models.Identity", "Identity")
                        .WithMany("BareBoardDetails")
                        .HasForeignKey("IId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Board", b =>
                {
                    b.HasOne("WEBAPIFLUENT.Models.Varient", "Varient")
                        .WithMany("Boards")
                        .HasForeignKey("VId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Varient");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Heading", b =>
                {
                    b.HasOne("WEBAPIFLUENT.Models.Identity", "Identity")
                        .WithMany("headings")
                        .HasForeignKey("IId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Identity", b =>
                {
                    b.HasOne("WEBAPIFLUENT.Models.Rivision", "Rivision")
                        .WithMany("Identity")
                        .HasForeignKey("RId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rivision");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.PowerUpTest", b =>
                {
                    b.HasOne("WEBAPIFLUENT.Models.Identity", "Identity")
                        .WithMany("PowerUpTest")
                        .HasForeignKey("IId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Rivision", b =>
                {
                    b.HasOne("WEBAPIFLUENT.Models.Board", "Board")
                        .WithMany("Rivisions")
                        .HasForeignKey("BId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.SubHeading", b =>
                {
                    b.HasOne("WEBAPIFLUENT.Models.Heading", "Heading")
                        .WithMany("SubHeading")
                        .HasForeignKey("HId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heading");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.SubHeadingImages", b =>
                {
                    b.HasOne("WEBAPIFLUENT.Models.SubHeading", "subHeading")
                        .WithMany("SubHeadingImages")
                        .HasForeignKey("SHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("subHeading");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Varient", b =>
                {
                    b.HasOne("WEBAPIFLUENT.Models.Product", "Product")
                        .WithMany("Varients")
                        .HasForeignKey("PId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.XLSheet", b =>
                {
                    b.HasOne("WEBAPIFLUENT.Models.XLTamplate", "XLTamplate")
                        .WithMany("Sheets")
                        .HasForeignKey("XId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("XLTamplate");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.XLTamplate", b =>
                {
                    b.HasOne("WEBAPIFLUENT.Models.SubHeading", "SubHeading")
                        .WithMany("XLTamplate")
                        .HasForeignKey("SHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubHeading");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Board", b =>
                {
                    b.Navigation("Rivisions");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Heading", b =>
                {
                    b.Navigation("SubHeading");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Identity", b =>
                {
                    b.Navigation("AssembledBoardDetails");

                    b.Navigation("BareBoardDetails");

                    b.Navigation("PowerUpTest");

                    b.Navigation("headings");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Product", b =>
                {
                    b.Navigation("Varients");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Rivision", b =>
                {
                    b.Navigation("Identity");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.SubHeading", b =>
                {
                    b.Navigation("SubHeadingImages");

                    b.Navigation("XLTamplate");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.Varient", b =>
                {
                    b.Navigation("Boards");
                });

            modelBuilder.Entity("WEBAPIFLUENT.Models.XLTamplate", b =>
                {
                    b.Navigation("Sheets");
                });
#pragma warning restore 612, 618
        }
    }
}
